"""Tests for the structure importer module."""

from __future__ import annotations

import numpy as np
import pytest
from pathlib import Path

from dft_forge.structure import (
    StructureImporter,
    ValidationReport,
    _detect_format_from_text,
    _parse_qe_input,
    _build_from_explicit,
)
from dft_forge.catalog import (
    build_dynamic_material_profile,
    build_dynamic_task_spec,
    register_dynamic_material,
    list_materials,
)


# ── Helpers ───────────────────────────────────────────────────────────────────

_SI_POSCAR = """Si lattice
1.0
5.43 0.00 0.00
2.715 4.697 0.00
2.715 2.349 4.288
Si
2
Direct
0.00 0.00 0.00 Si
0.25 0.25 0.25 Si
"""

_SI_XYZ = """2
Si generated by StructureImporter
Si 0.000 0.000 0.000
Si 1.3575 2.3485 2.1440
"""

_SI_QE = """&control
  calculation = 'vc-relax'
  prefix = 'si'
/
&system
  ibrav = 0
  nat = 2
  ntyp = 1
  ecutwfc = 25.0
  ecutrho = 200.0
/
&electrons
  conv_thr = 1.0d-8
/
ATOMIC_SPECIES
Si 28.086 Si_r.upf
ATOMIC_POSITIONS (crystal)
Si 0.0000000000 0.0000000000 0.0000000000
Si 0.2500000000 0.2500000000 0.2500000000
CELL_PARAMETERS (bohr)
5.4300000000 0.0000000000 0.0000000000
2.7150000000 4.6970000000 0.0000000000
2.7150000000 2.3485000000 4.2880000000
K_POINTS automatic
4 4 4 1 1 1
"""

_SI_CIF = """data_Si
_cell_length_a 5.43
_cell_length_b 5.43
_cell_length_c 5.43
_cell_angle_alpha 90
_cell_angle_beta 90
_cell_angle_gamma 90
_symmetry_space_group_name_H-M 'Fd-3m'
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Si1 Si 0.000 0.000 0.000
Si2 Si 0.250 0.250 0.250
"""


def _write_text(tmp_path: Path, name: str, content: str) -> Path:
    p = tmp_path / name
    p.write_text(content)
    return p


# ── Format detection ──────────────────────────────────────────────────────────

class TestFormatDetection:
    def test_detect_poscar(self):
        assert _detect_format_from_text("POSCAR\nSi\n1.0\n...") == "poscar"

    def test_detect_atom_block(self):
        assert _detect_format_from_text("ATOM\nSi 0 0 0\n") == "poscar"

    def test_detect_direct_keyword(self):
        assert _detect_format_from_text("Direct\nSi 0 0 0\n") == "poscar"

    def test_detect_qe_sections(self):
        text = "ATOMIC_SPECIES\nATOMIC_POSITIONS (crystal)\n"
        assert _detect_format_from_text(text) == "qe_input"

    def test_detect_xyz(self):
        text = "2\ncomment\nSi 0 0 0\nSi 1 1 1\n"
        assert _detect_format_from_text(text) == "xyz"

    def test_detect_unknown(self):
        assert _detect_format_from_text("hello world") == "unknown"


# ── CIF parser ───────────────────────────────────────────────────────────────

class TestParseCIF:
    def test_si_cif(self, tmp_path: Path):
        importer = StructureImporter()
        p = _write_text(tmp_path, "si.cif", _SI_CIF)
        report = importer.import_structure(p)
        assert report.success is True
        assert report.format == "cif"
        assert report.formula == "Si2"
        assert report.natoms == 2

    def test_cif_invalid_element_raises(self, tmp_path: Path):
        cif = """data_Bad
_cell_length_a 3.0
loop_
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Xx 0 0 0
"""
        importer = StructureImporter()
        p = _write_text(tmp_path, "bad.cif", cif)
        report = importer.import_structure(p)
        assert report.success is False
        assert any("Parsing failed" in e or "Unsupported element symbol" in e for e in report.errors)


# ── POSCAR parser ─────────────────────────────────────────────────────────────

class TestParsePOSCAR:
    def test_si_poscar_file(self, tmp_path: Path):
        importer = StructureImporter()
        p = _write_text(tmp_path, "POSCAR", _SI_POSCAR)
        report = importer.import_structure(p)
        assert report.success is True
        assert report.format == "poscar"
        assert report.formula == "Si2"
        assert report.natoms == 2

    def test_si_poscar_string(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_POSCAR, format="poscar")
        assert report.success is True
        assert report.natoms == 2


# ── XYZ parser ────────────────────────────────────────────────────────────────

class TestParseXYZ:
    def test_si_xyz_file(self, tmp_path: Path):
        importer = StructureImporter()
        p = _write_text(tmp_path, "si.xyz", _SI_XYZ)
        report = importer.import_structure(p)
        assert report.format == "xyz"
        assert report.success is False
        assert any("Invalid cell" in e or "not periodic" in e for e in report.errors)

    def test_si_xyz_string(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_XYZ, format="xyz")
        assert report.format == "xyz"
        assert report.success is False
        assert any("Invalid cell" in e or "not periodic" in e for e in report.errors)


# ── QE input parser ───────────────────────────────────────────────────────────

class TestParseQEInput:
    def test_si_qe_file(self, tmp_path: Path):
        importer = StructureImporter()
        p = _write_text(tmp_path, "si.in", _SI_QE)
        report = importer.import_structure(p)
        assert report.success is True
        assert report.format == "qe_input"
        assert report.natoms == 2

    def test_si_qe_string(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_QE, format="qe_input")
        assert report.success is True
        assert report.formula == "Si2"

    def test_qe_missing_positions_raises(self, tmp_path: Path):
        text = "CELL_PARAMETERS (bohr)\n1 0 0\n0 1 0\n0 0 1\n"
        with pytest.raises(ValueError, match="no ATOMIC_POSITIONS"):
            _parse_qe_input(text)


# ── Explicit structure parser ─────────────────────────────────────────────────

class TestExplicitStructure:
    def test_valid_explicit(self):
        source = {
            "lattice": [[4.0, 0, 0], [0, 4.0, 0], [0, 0, 4.0]],
            "positions": [[0, 0, 0], [2, 2, 2]],
            "symbols": ["Si", "Si"],
            "fractional": False,
        }
        atoms = _build_from_explicit(**source)
        assert len(atoms) == 2
        assert atoms.get_chemical_symbols() == ["Si", "Si"]

    def test_fractional_positions(self):
        source = {
            "lattice": [[4.0, 0, 0], [0, 4.0, 0], [0, 0, 4.0]],
            "positions": [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]],
            "symbols": ["Si", "Si"],
            "fractional": True,
        }
        atoms = _build_from_explicit(**source)
        assert len(atoms) == 2
        expected = np.array([[0.0, 0.0, 0.0], [2.0, 2.0, 2.0]])
        assert np.allclose(atoms.get_positions(), expected)


# ── Validation rules ──────────────────────────────────────────────────────────

class TestValidation:
    def test_valid_structure_success(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_QE, format="qe_input")
        assert report.success is True
        assert report.nspecies == 1
        assert report.space_group is not None

    def test_non_periodic_rejected(self):
        importer = StructureImporter()
        from ase import Atoms as AseAtoms
        atoms = AseAtoms("Si2", positions=[[0, 0, 0], [1, 1, 1]], pbc=False)
        report = ValidationReport(success=False)
        from dft_forge.structure import _validate_periodicity
        report.errors.extend(_validate_periodicity(atoms))
        assert report.errors
        assert any("not periodic" in e for e in report.errors)

    def test_unsupported_element_rejected(self, tmp_path: Path):
        cif = """data_Bad
_cell_length_a 3.0
loop_
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Xx 0 0 0
"""
        importer = StructureImporter()
        p = _write_text(tmp_path, "bad.cif", cif)
        report = importer.import_structure(p)
        assert report.success is False
        assert any("Parsing failed" in e or "Unsupported element symbol" in e for e in report.errors)

    def test_unknown_format_rejected(self):
        importer = StructureImporter()
        report = importer.import_structure("this is not a structure", format="unknown")
        assert report.success is False
        assert any("Unsupported or unknown structure format" in e for e in report.errors)

    def test_too_close_atoms_rejected(self):
        source = {
            "lattice": [[10, 0, 0], [0, 10, 0], [0, 0, 10]],
            "positions": [[0, 0, 0], [0.01, 0.01, 0.01]],
            "symbols": ["Si", "Si"],
            "fractional": False,
        }
        importer = StructureImporter(min_nearest_neighbor_angstrom=0.8)
        report = importer.import_structure(source, format="explicit")
        assert report.success is False
        assert any("Nearest-neighbor distance" in e for e in report.errors)


# ── Dynamic catalog helpers ───────────────────────────────────────────────────

class TestDynamicCatalog:
    def test_build_dynamic_profile_from_valid_report(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_QE, format="qe_input")
        assert report.success is True
        profile = build_dynamic_material_profile(
            report,
            pseudos={"Si": "Si_r.upf"},
            is_metal=False,
        )
        assert profile.formula == "Si2"
        assert profile.ibrav == 0
        assert profile.nspecies == 1
        assert profile.pseudos == {"Si": "Si_r.upf"}

    def test_build_dynamic_profile_from_failed_report_raises(self):
        report = ValidationReport(success=False, atoms=None)
        with pytest.raises(ValueError, match="failed validation report"):
            build_dynamic_material_profile(report)

    def test_register_dynamic_material(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_QE, format="qe_input")
        profile = build_dynamic_material_profile(
            report,
            pseudos={"Si": "Si_r.upf"},
            is_metal=False,
        )
        before = list_materials()
        register_dynamic_material("dyn_Si2", profile)
        after = list_materials()
        assert "dyn_Si2" in after
        assert after.index("dyn_Si2") > after.index("Si")
        # Cleanup to avoid polluting later tests if module state persists.
        from dft_forge.catalog import MATERIALS
        MATERIALS.pop("dyn_Si2", None)

    def test_build_dynamic_task_spec(self):
        importer = StructureImporter()
        report = importer.import_structure(_SI_QE, format="qe_input")
        profile = build_dynamic_material_profile(
            report,
            pseudos={"Si": "Si_r.upf"},
            is_metal=False,
        )
        spec = build_dynamic_task_spec(
            "T1_dyn_Si2_vcrelax",
            profile,
            task_type="T1",
            parameters={"ecutwfc": 20.0},
        )
        assert spec.task_id == "T1_dyn_Si2_vcrelax"
        assert spec.material_profile.formula == "Si2"
        assert spec.metadata.get("dynamic") is True
