#!/usr/bin/env python3
"""Generate dft_forge/catalog/library.py from the verified M1 materials YAML.

Source: inspect_dft_agent bench/materials/m1_resolved.yaml (58 Materials
Project-verified structures). Built-in catalog materials (Si/Al/MgO) keep
their hand-tuned entries; everything else becomes a library entry using
GBRV USPP PBE pseudopotentials.

Usage:
    python scripts/gen_material_library.py <path-to-m1_resolved.yaml>
"""

import sys
from pathlib import Path

import yaml
from ase.data import atomic_masses, atomic_numbers

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "dft_forge" / "catalog" / "library.py"

BUILTIN = {"Si", "Al", "MgO"}
METAL_CATEGORIES = {"simple_metals", "nonmagnetic_transition_metals"}
ECUT_OVERRIDES = {"H": 60.0, "C": 60.0, "N": 60.0, "O": 60.0, "F": 60.0, "B": 50.0, "Be": 50.0}
DEFAULT_ECUT = 45.0
ECUTRHO_FACTOR = 8.0


def species_of(formula: str):
    from ase.formula import Formula

    return [str(s) for s in Formula(formula).count().keys()]


def mass_of(element: str) -> float:
    return float(atomic_masses[atomic_numbers[element]])


def defaults(cellpar, is_metal: bool):
    a, b, c, alpha, beta, gamma = cellpar
    if is_metal:
        kpoints = [8, 8, 8, 1, 1, 1]
    elif abs(gamma - 120.0) < 1.0:  # hexagonal family
        kpoints = [6, 6, 4, 1, 1, 1]
    elif abs(a - b) < 1e-6 and abs(a - c) > 1e-6 and abs(gamma - 90.0) < 1.0:  # tetragonal
        kpoints = [6, 6, 8, 1, 1, 1]
    else:
        kpoints = [6, 6, 6, 1, 1, 1]
    return kpoints


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if not src or not src.exists():
        print(__doc__)
        return 1

    data = yaml.safe_load(src.read_text())
    entries = {}
    skipped = []
    for cat_name, cat in data["M1"]["categories"].items():
        for m in cat["materials"]:
            formula = m["formula"]
            if formula in BUILTIN:
                skipped.append(formula)
                continue
            mp = m["initial_structure_from_mp"]
            cellpar = [
                float(mp["lattice_a"]),
                float(mp["lattice_b"]),
                float(mp["lattice_c"]),
                float(mp["alpha"]),
                float(mp["beta"]),
                float(mp["gamma"]),
            ]
            sites = [[s["element"], [float(x) for x in s["position"]]] for s in mp["sites"]]
            species = species_of(formula)
            is_metal = cat_name in METAL_CATEGORIES
            ecut = max(ECUT_OVERRIDES.get(el, DEFAULT_ECUT) for el in species)
            entries[formula] = {
                "formula": formula,
                "structure_type": m.get("structure_hint", "unknown"),
                "space_group": m.get("space_group", ""),
                "mp_id": m.get("mp_id", ""),
                "name": m.get("name", ""),
                "ibrav": 0,
                "cellpar": cellpar,
                "sites": sites,
                "nspecies": len(species),
                "species": species,
                "masses": [mass_of(el) for el in species],
                "pseudos": {el: f"{el}.upf" for el in species},
                "occupations": "smearing",
                "smearing": "mp",
                "degauss": 0.02 if is_metal else 0.01,
                "ecutwfc_default": ecut,
                "ecutrho_default": round(ecut * ECUTRHO_FACTOR, 1),
                "kpoints_default": tuple(defaults(cellpar, is_metal)),
                "is_metal": is_metal,
                "category": cat_name,
            }

    lines = [
        '"""Material library: MP-verified structures with GBRV USPP PBE pseudos.',
        "",
        "Auto-generated by scripts/gen_material_library.py from the verified",
        "M1 materials list (inspect_dft_agent bench). Do not edit by hand.",
        "Structure data: fractional `sites` + `cellpar` (a, b, c, alpha, beta,",
        "gamma in Angstrom/degrees) from Materials Project ground-state cells.",
        '"""',
        "",
        "from typing import Any, Dict",
        "",
        "LIBRARY_MATERIALS: Dict[str, Dict[str, Any]] = {",
    ]
    for formula in sorted(entries):
        db = entries[formula]
        lines.append(f"    {formula!r}: {{")
        order = [
            "formula", "structure_type", "space_group", "mp_id", "name", "ibrav",
            "cellpar", "sites", "nspecies", "species", "masses", "pseudos",
            "occupations", "smearing", "degauss", "ecutwfc_default",
            "ecutrho_default", "kpoints_default", "is_metal", "category",
        ]
        for key in order:
            val = db[key]
            if key == "kpoints_default":
                val = list(val)
            lines.append(f"        {key!r}: {val!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines))

    n_metal = sum(1 for e in entries.values() if e["is_metal"])
    print(f"wrote {len(entries)} materials ({n_metal} metals) -> {OUT}")
    print(f"skipped built-ins: {sorted(set(skipped))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
